-- ====================================================================
-- College Event Registration Management System - Supabase PostgreSQL Schema
-- ====================================================================

-- 1. Users Table (Authorized Staff and Administrators)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    username VARCHAR(80) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Sessions Table (Session Token Authentication)
CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. Events Table (Event Details and Auto-Generated Code EV-###)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    event_date DATE NOT NULL,
    details VARCHAR(500) DEFAULT '' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 4. Students Table (Participant Directory)
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(120) NOT NULL,
    details VARCHAR(500) DEFAULT '' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 5. Registrations Table (Relational link between Students and Events)
-- Constraint uq_student_event enforces NFR-07 (0 duplicate registrations)
CREATE TABLE IF NOT EXISTS registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_pk BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT uq_student_event UNIQUE (student_pk, event_id)
);

-- Performance and Lookup Indexes
CREATE INDEX IF NOT EXISTS idx_users_username ON users (LOWER(username));
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions (token);
CREATE INDEX IF NOT EXISTS idx_events_code ON events (code);
CREATE INDEX IF NOT EXISTS idx_events_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_students_student_id ON students (LOWER(student_id));
CREATE INDEX IF NOT EXISTS idx_registrations_event ON registrations (event_id);
CREATE INDEX IF NOT EXISTS idx_registrations_student ON registrations (student_pk);

-- Row Level Security (RLS) Policy Setup
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

-- Allow service role full access and authenticated/anon access for backend API integration
CREATE POLICY "Allow all access to backend for users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to backend for sessions" ON sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to backend for events" ON events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to backend for students" ON students FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to backend for registrations" ON registrations FOR ALL USING (true) WITH CHECK (true);

-- Seed Initial Data if empty (admin / admin123)
INSERT INTO users (full_name, username, password_hash)
VALUES (
    'Authorized User',
    'admin',
    'b8eaf8c453eb7792f3942b796581b6e4$37c7e7b06abb1365290bc142e15bab04f247c9ed3bcf765fe4d0d7eeb91d81c4'
)
ON CONFLICT (username) DO NOTHING;

INSERT INTO events (code, name, event_date, details)
VALUES 
    ('EV-001', 'Technical Symposium', '2026-09-10', 'College technical event with coding contests and workshops'),
    ('EV-002', 'Cultural Fest', '2026-09-15', 'College cultural celebration with music and performing arts'),
    ('EV-003', 'Sports Meet', '2026-09-20', 'College annual athletics and team sports events'),
    ('EV-004', 'Project Expo', '2026-09-25', 'Student engineering and science project exhibition'),
    ('EV-005', 'Coding Contest', '2026-10-02', 'Annual algorithmic and competitive programming challenge'),
    ('EV-006', 'Quiz Competition', '2026-10-05', 'Inter-department general and technical trivia quiz')
ON CONFLICT (code) DO NOTHING;

INSERT INTO students (student_id, name, details)
VALUES
    ('STU001', 'Arun Kumar', 'Computer Science and Engineering'),
    ('STU002', 'Priya S', 'Electronics and Communication'),
    ('STU003', 'Rahul M', 'Information Technology'),
    ('STU004', 'Divya R', 'Mechanical Engineering'),
    ('STU005', 'Karthik P', 'Civil Engineering')
ON CONFLICT (student_id) DO NOTHING;

-- Enable Realtime for events, registrations, and students in Supabase publication
ALTER PUBLICATION supabase_realtime ADD TABLE events;
ALTER PUBLICATION supabase_realtime ADD TABLE registrations;
ALTER PUBLICATION supabase_realtime ADD TABLE students;

-- Set REPLICA IDENTITY FULL for complete payload delivery on UPDATE and DELETE
ALTER TABLE events REPLICA IDENTITY FULL;
ALTER TABLE registrations REPLICA IDENTITY FULL;
ALTER TABLE students REPLICA IDENTITY FULL;
